### ISSUE TITLE
Bad username/password

### ISSUE THREAD

**Issue by bdparrish** [taigaio/taiga-vagrant#20]
admin/123123 is not the correct credentials combo

<img width="489" alt="screen shot 2015-10-06 at 12 52 35 pm" src="https://cloud.githubusercontent.com/assets/720788/10315582/29b49b3c-6c29-11e5-9983-5841a209fa9d.png">

**Comment by bameda** [comment]
This error is because your taiga-front can't connect with your taiga-back

See the broweser console to show errors and request/responses between taiga-back and taiga-front and check taat taiga back is running properly (the host and port of taiga-back is right in taiga-front-dist/js/conf.json).

**Comment by bdparrish** [comment]
I see that my `vagrant up` errored out now.

```
==> default: ----------------------------------------
==> default: Cleaning up...
==> default: Command /home/vagrant/.virtualenvs/taiga/bin/python3.4 -c "import setuptools, tokenize;__file__='/home/vagrant/.virtualenvs/taiga/build/psycopg2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-nbfpe4q_-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/vagrant/.virtualenvs/taiga/include/site/python3.4 failed with error code 1 in /home/vagrant/.virtualenvs/taiga/build/psycopg2
==> default: Storing debug log for failure in /home/vagrant/.pip/pip.log
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 94, in __init__
==> default:     mod = importlib.import_module(self.SETTINGS_MODULE)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
==> default:     return _bootstrap._gcd_import(name[level:], package, level)
==> default:   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
==> default:   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
==> default:   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1129, in _exec
==> default:   File "<frozen importlib._bootstrap>", line 1471, in exec_module
==> default:   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
==> default:   File "/home/vagrant/taiga-back/settings/__init__.py", line 20, in <module>
==> default:     from .celery import *
==> default:   File "/home/vagrant/taiga-back/settings/celery.py", line 17, in <module>
==> default:     from kombu import Exchange, Queue
==> default: ImportError: No module named 'kombu'
==> default: 
==> default: During handling of the above exception, another exception occurred:
==> default: 
==> default: Traceback (most recent call last):
==> default:   File "manage.py", line 10, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
==> default:     settings.INSTALLED_APPS
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 46, in __getattr__
==> default:     self._setup(name)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 42, in _setup
==> default:     self._wrapped = Settings(settings_module)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 98, in __init__
==> default:     % (self.SETTINGS_MODULE, e)
==> default: ImportError: Could not import settings 'settings' (Is it on sys.path? Is there an import error in the settings file?): No module named 'kombu'
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 94, in __init__
==> default:     mod = importlib.import_module(self.SETTINGS_MODULE)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
==> default:     return _bootstrap._gcd_import(name[level:], package, level)
==> default:   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
==> default:   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
==> default:   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1129, in _exec
==> default:   File "<frozen importlib._bootstrap>", line 1471, in exec_module
==> default:   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
==> default:   File "/home/vagrant/taiga-back/settings/__init__.py", line 20, in <module>
==> default:     from .celery import *
==> default:   File "/home/vagrant/taiga-back/settings/celery.py", line 17, in <module>
==> default:     from kombu import Exchange, Queue
==> default: ImportError: No module named 'kombu'
==> default: 
==> default: During handling of the above exception, another exception occurred:
==> default: 
==> default: Traceback (most recent call last):
==> default:   File "manage.py", line 10, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
==> default:     settings.INSTALLED_APPS
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 46, in __getattr__
==> default:     self._setup(name)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 42, in _setup
==> default:     self._wrapped = Settings(settings_module)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 98, in __init__
==> default:     % (self.SETTINGS_MODULE, e)
==> default: ImportError: Could not import settings 'settings' (Is it on sys.path? Is there an import error in the settings file?): No module named 'kombu'
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 94, in __init__
==> default:     mod = importlib.import_module(self.SETTINGS_MODULE)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
==> default:     return _bootstrap._gcd_import(name[level:], package, level)
==> default:   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
==> default:   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
==> default:   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1129, in _exec
==> default:   File "<frozen importlib._bootstrap>", line 1471, in exec_module
==> default:   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
==> default:   File "/home/vagrant/taiga-back/settings/__init__.py", line 20, in <module>
==> default:     from .celery import *
==> default:   File "/home/vagrant/taiga-back/settings/celery.py", line 17, in <module>
==> default:     from kombu import Exchange, Queue
==> default: ImportError: No module named 'kombu'
==> default: 
==> default: During handling of the above exception, another exception occurred:
==> default: 
==> default: Traceback (most recent call last):
==> default:   File "manage.py", line 10, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
==> default:     settings.INSTALLED_APPS
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 46, in __getattr__
==> default:     self._setup(name)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 42, in _setup
==> default:     self._wrapped = Settings(settings_module)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 98, in __init__
==> default:     % (self.SETTINGS_MODULE, e)
==> default: ImportError: Could not import settings 'settings' (Is it on sys.path? Is there an import error in the settings file?): No module named 'kombu'
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 94, in __init__
==> default:     mod = importlib.import_module(self.SETTINGS_MODULE)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
==> default:     return _bootstrap._gcd_import(name[level:], package, level)
==> default:   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
==> default:   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
==> default:   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1129, in _exec
==> default:   File "<frozen importlib._bootstrap>", line 1471, in exec_module
==> default:   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
==> default:   File "/home/vagrant/taiga-back/settings/__init__.py", line 20, in <module>
==> default:     from .celery import *
==> default:   File "/home/vagrant/taiga-back/settings/celery.py", line 17, in <module>
==> default:     from kombu import Exchange, Queue
==> default: ImportError: No module named 'kombu'
==> default: 
==> default: During handling of the above exception, another exception occurred:
==> default: 
==> default: Traceback (most recent call last):
==> default:   File "manage.py", line 10, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
==> default:     settings.INSTALLED_APPS
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 46, in __getattr__
==> default:     self._setup(name)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 42, in _setup
==> default:     self._wrapped = Settings(settings_module)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 98, in __init__
==> default:     % (self.SETTINGS_MODULE, e)
==> default: ImportError: Could not import settings 'settings' (Is it on sys.path? Is there an import error in the settings file?): No module named 'kombu'
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 94, in __init__
==> default:     mod = importlib.import_module(self.SETTINGS_MODULE)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
==> default:     return _bootstrap._gcd_import(name[level:], package, level)
==> default:   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
==> default:   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
==> default:   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1129, in _exec
==> default:   File "<frozen importlib._bootstrap>", line 1471, in exec_module
==> default:   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
==> default:   File "/home/vagrant/taiga-back/settings/__init__.py", line 20, in <module>
==> default:     from .celery import *
==> default:   File "/home/vagrant/taiga-back/settings/celery.py", line 17, in <module>
==> default:     from kombu import Exchange, Queue
==> default: ImportError: No module named 'kombu'
==> default: 
==> default: During handling of the above exception, another exception occurred:
==> default: 
==> default: Traceback (most recent call last):
==> default:   File "manage.py", line 10, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
==> default:     settings.INSTALLED_APPS
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 46, in __getattr__
==> default:     self._setup(name)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 42, in _setup
==> default:     self._wrapped = Settings(settings_module)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 98, in __init__
==> default:     % (self.SETTINGS_MODULE, e)
==> default: ImportError: Could not import settings 'settings' (Is it on sys.path? Is there an import error in the settings file?): No module named 'kombu'
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 94, in __init__
==> default:     mod = importlib.import_module(self.SETTINGS_MODULE)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
==> default:     return _bootstrap._gcd_import(name[level:], package, level)
==> default:   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
==> default:   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
==> default:   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1129, in _exec
==> default:   File "<frozen importlib._bootstrap>", line 1471, in exec_module
==> default:   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
==> default:   File "/home/vagrant/taiga-back/settings/__init__.py", line 20, in <module>
==> default:     from .celery import *
==> default:   File "/home/vagrant/taiga-back/settings/celery.py", line 17, in <module>
==> default:     from kombu import Exchange, Queue
==> default: ImportError: No module named 'kombu'
==> default: 
==> default: During handling of the above exception, another exception occurred:
==> default: 
==> default: Traceback (most recent call last):
==> default:   File "manage.py", line 10, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
==> default:     settings.INSTALLED_APPS
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 46, in __getattr__
==> default:     self._setup(name)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 42, in _setup
==> default:     self._wrapped = Settings(settings_module)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 98, in __init__
==> default:     % (self.SETTINGS_MODULE, e)
==> default: ImportError: Could not import settings 'settings' (Is it on sys.path? Is there an import error in the settings file?): No module named 'kombu'
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 94, in __init__
==> default:     mod = importlib.import_module(self.SETTINGS_MODULE)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
==> default:     return _bootstrap._gcd_import(name[level:], package, level)
==> default:   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
==> default:   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
==> default:   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 1129, in _exec
==> default:   File "<frozen importlib._bootstrap>", line 1471, in exec_module
==> default:   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
==> default:   File "/home/vagrant/taiga-back/settings/__init__.py", line 20, in <module>
==> default:     from .celery import *
==> default:   File "/home/vagrant/taiga-back/settings/celery.py", line 17, in <module>
==> default:     from kombu import Exchange, Queue
==> default: ImportError: No module named 'kombu'
==> default: 
==> default: During handling of the above exception, another exception occurred:
==> default: 
==> default: Traceback (most recent call last):
==> default:   File "manage.py", line 10, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
==> default:     settings.INSTALLED_APPS
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 46, in __getattr__
==> default:     self._setup(name)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 42, in _setup
==> default:     self._wrapped = Settings(settings_module)
==> default:   File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/conf/__init__.py", line 98, in __init__
==> default:     % (self.SETTINGS_MODULE, e)
==> default: ImportError: Could not import settings 'settings' (Is it on sys.path? Is there an import error in the settings file?): No module named 'kombu'
```

Is this something I need to fix on my end?

**Comment by bameda** [comment]
Something went wrong during the setup process because you have missing dependencies.

Try to reinstall it again.

**Comment by bdparrish** [comment]
I have run `setup-server.sh` twice now with the same errors as the `vagrant ssh` command.

**Comment by bameda** [comment]
I find a problem in the ubuntu server when vagrant try to install python3-dev

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo apt-get install  python3 python3-pip python-dev python3-dev python-pip virtualenvwrapper libxml2-dev libxslt1-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxslt1-dev is already the newest version.
python-dev is already the newest version.
python3 is already the newest version.
libxml2-dev is already the newest version.
python-pip is already the newest version.
python3-pip is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-dev : Depends: libpython3-dev (= 3.4.0-0ubuntu2) but it is not going to be installed
               Depends: python3.4-dev (>= 3.4.0-0~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Taiga need this packages rto run.

I'm working on it.

**Comment by bameda** [comment]
This is a problem with ubuntu vagrant image. It has a invalid version of python3 installed and is bigger than the candidated version of python3-dev. So I do that to fix it.

1. Uninstall python3

   ```
   vagrant ssh
   sudo apt-get remove --purge python3 libpython3.4-stdlib python3.4* 
   # Say 'yes' to all questions
   ````
2. Reinstall python3

   ```
   sudo apt-get install python3 python3-pip python-dev python3-dev python-pip    virtualenvwrapper libxml2-dev libxslt1-dev
   ```
3. Reinstall taiga-back dependencies

   ```
   cd taiga-back/
   workon taiga
   pip install --upgrade -r requirements-devel.txt
   ```
4. Regenerate the db

   ```
   bash ./regenerate.sh
   ```
5.  Restart the vagrant box

   ```
   vagrant halt 
   vagran up
   ```

And now test it again

**Comment by bameda** [comment]
Hi @bdparrish,

Ubuntu has fixed the box image and now works properly. So you have to create it again: 

```
vagrant destroy
rm -rf ~/.vagrant.d/boxes/trusty64/
vagrant up
```
